### ISSUE TITLE
Group endpoints by poll id

### ISSUE THREAD

**Issue by roipoussiere** [MieuxVoter/mv-api-spec#1]
This is the current API schema in a nutshell:

- **PATCH** ​`/polls​/{pollId}` *Updates a poll*
- **DELETE** `​/polls​/{pollId}` *Deletes a poll*
- **POST** `/judgments​/{pollId}` *Creates a judgment*
- **GET** ​`/judgments​/{judgmentId}` *Gets a judgment by ID*
- **DELETE** `/judgments​/{judgmentId}` *Deletes a judgment*
- **POST** ​`/invites​/{pollId}` *Invite a judge to a poll*
- **GET** `/results​/{pollId}` *Get the results of a poll*

There are some resources that refers to a poll id, or a judgement id.

If you add other functionalities / resources over the next few year, you are going to add many other endpoints: `POST /something/{poll-id}`, `GET /something-else/{poll-id}`, and the API structure will become a mess.

It sounds better to start from the object and then describe the action to do with, instead of starting from the action and then referring to the object.

Also, since a RestFul API is supposed to be auto-descriptive, the endpoint `/polls/{poll-id}` could be a good place to add links about all other actions available on this poll (add a judgement, etc.).

For instance, take a look at the GitLab API, that follow this convention like many others: https://docs.gitlab.com/ee/api/api_resources.html

That said, the API schema could be like this:

- **PATCH** ​`/polls​/{pollId}` *Updates a poll*
- **DELETE** `​/polls​/{pollId}` *Deletes a poll*
- **POST** `/polls/{pollId}/judgments​` *Creates a judgment*
- **POST** ​`/polls/{pollId}/invites` *Invite a judge to a poll*
- **GET** `/polls​/{pollId}/results` *Get the results of a poll*
- **GET** ​`/judgments​/{judgmentId}` *Gets a judgment by ID*
- **DELETE** `/judgments​/{judgmentId}` *Deletes a judgment*

**Comment by guhur** [comment]
Sounds good to me as well
