### ISSUE TITLE
use kebab-case naming convention

### ISSUE THREAD

**Issue by roipoussiere** [MieuxVoter/mv-api-spec#2]
On many typos, the uppercase "I" can be confused with the lowercase "L", so `pollId` can be confusing.

By using kebab-case naming convention, `poll-id` and `judgment-id` are more explicit and easier to read.

**Comment by guhur** [comment]
That sounds good to me. 

It seems that [both naming convention are acceptable](https://restfulapi.net/resource-naming/ ), but your point is more than fair.
