### ISSUE TITLE
Rename invite to judge

### ISSUE THREAD

**Issue by roipoussiere** [MieuxVoter/mv-api-spec#4]
Following #1, we now have this:

**POST** ​`/polls/{pollId}/invites` *Invite a judge to a poll*

In order to keep thinking in terms of resources, I suggest to rename *invite* to *judge*:

**POST** ​`/polls/{pollId}/judge` *Add a judge to a poll*

This also allow future operations about this judge on this poll.

**Comment by guhur** [comment]
I am OK with changing the name, but I don't like judge. When I read it first, I was thinking that this endpoint was about judging a poll (so what #1 calls `POST /polls/{pollId}/judgments`).
What do you think?

**Comment by roipoussiere** [comment]
*Judge* was reffering to the `Judge` component, before you renamed it to `Invite`. :)

But I don't really like this new name, because its a verb. API verbs are used to be http verbs, like GET, POST, etc. and resources are usually nouns.

If you want to keep a resource name related to *invite*, you may use *invitation*. The action of *GETing invitations* makes more sense than *GETing invite*.

That said, I personally prefer resources names related to a person, such as *participant*, *respondent* or *voter*. Because we say that a person participate to a poll, this is not the invitation that do it. It also anticipates API evolution such as the ability to know if a specific person already participated or not to a poll.

**Comment by guhur** [comment]
Actually I think the word we are looking for is `jury`. 

A judge is more the unit that computes the ranking over MJ. A jury is someone who participates in the deliberation.

I doubt that any UI would employ this terminology, but it sounds pretty clear for the API, no?

**Comment by roipoussiere** [comment]
The problem with jury is it represents a group of people, not a single person. We want to get / add   /... single persons.

`jury-member` could be fine.

I think I prefer `participant` over `jury-member` because it's a unique word, but it's just a personal preference.

**Comment by roipoussiere** [comment]
A discussion about MieuxVoter terminology (including the word defining a jury member) has started on the [Mieux voter Forum (fr)](https://forum.mieuxvoter.fr/t/terminologie-mieuxvoter/42).

**Comment by roipoussiere** [comment]
Based on the discussion linked above, I suggest the following new terminology for the API:

- poll
- participate
- ballot
- proposal
- participants
- results
- mention

Is it ok for you? If yes I can add commits to renames terms on the PR I'm working on.

**Comment by guhur** [comment]
Sounds good to me :)
