### ISSUE TITLE
specify expected data format

### ISSUE THREAD

**Issue by roipoussiere** [MieuxVoter/mv-api-spec#7]
The [OpenAPI specification](https://swagger.io/docs/specification/data-models/data-types/) allows many ways to specify how each data should be.

#6 is a first step, but many other things can be done:
- string min/max size;
- string patterns, etc.

This helps OpenAPI tools to know more things about this API, and tends to define a precise protocol that other applications could follow to interact with mieux-voter API.

**Comment by guhur** [comment]
I think your last PR covers good enough this issue. Let's open other issue if we want to expand this idea.
